version: '3'
services:
  db:
    image: postgres:9.6
    volumes:
      - pp-db:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASS}
    ports:
      - "5432:5432"

  web:
    build: .
    command: bash -l -c "rake db:migrate && rake db:seed && foreman start"
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    env_file:
      - .env
    environment:
      DATABASE_HOST: db
      REDIS_URL: redis://cache:6379/0
    depends_on:
      - db
      - cache

  cache:
    image: redis:6.2-alpine
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning

  swagger:
    image: swaggerapi/swagger-ui
    ports:
      - "8080:8080"
    environment:
      API_URL: http://localhost:3000/api/v1/swagger_doc.json

volumes:
  pp-db: